# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 15.5
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# use_frameworks! :linkage => :static
# $RNFirebaseAsStaticFramework = true
# dynamic_frameworks = ['VisionCamera', 'RNWorklets']
create_search_paths = ['VisionCamera']
add_search_paths = ['RNWorklets']

# Make all the other frameworks into static frameworks by overriding the static_framework function to return true
# pre_install do |installer|
#   installer.pod_targets.each do |pod|
#     if dynamic_frameworks.include?(pod.name)
#       def pod.build_type;
#         Pod::BuildType.static_library
#       end
#     end
#   end
# end

target 'Interns' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  use_modular_headers!
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'Interns-Dev' do
    inherit! :complete
  end

  target 'Interns-Rc' do
    inherit! :complete
  end

  target 'Interns-Stg' do
    inherit! :complete
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    installer.pods_project.targets.each do |target|
      if create_search_paths.include?(target.name)
        target.build_configurations.each do |config|
          # Add a header search path
          config.build_settings['HEADER_SEARCH_PATHS'] ||= []
          config.build_settings['HEADER_SEARCH_PATHS'] << '$(inherited)'
          config.build_settings['HEADER_SEARCH_PATHS'] << '"${REACT_NATIVE_PATH}/ReactCommon/runtimeexecutor"' # Add your path here

          # Add a framework search path (if needed)
          # config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= '$(inherited)'
          # config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '\n"${REACT_NATIVE_PATH}/ReactCommon/runtimeexecutor"' # Add your path here
        end
      end
      if add_search_paths.include?(target.name)
        target.build_configurations.each do |config|
          # Add a header search path
          config.build_settings['HEADER_SEARCH_PATHS'] << '"${REACT_NATIVE_PATH}/ReactCommon/runtimeexecutor"' # Add your path here
        end
      end
    end
  end
end
